pipeline {
    agent any

    tools {
        maven "MAVEN"   // Must match Jenkins Maven tool configuration
        jdk "JDK-17"    // Use JDK 17 installed in Jenkins
    }

    environment {
        DOCKER_IMAGE = "rukevweubio/web-application"
        DOCKER_TAG = "latest"
        DOCKER_CREDENTIAL_ID = "docker_hub"
        GIT_BRANCH = "main"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${GIT_BRANCH}", url: "https://github.com/rukevweubio/Jenkins-Maven-Docker-ECR-Pipeline.git"
            }
        }

        stage('Maven Build') {
            steps {
                dir('my-webapp') {
                    sh "mvn clean package -DskipTests"
                }
            }
        }

        stage('Run JUnit Tests') {
            steps {
                dir('my-webapp') {
                    sh "mvn test"
                }
            }
            post {
                always {
                    // Publish JUnit test results
                    junit 'my-webapp/target/surefire-reports/*.xml'
                }
            }
        }

        stage('JaCoCo Coverage') {
            steps {
                dir('my-webapp') {
                    sh "mvn jacoco:report"
                }
            }
            post {
                always {
                    // Publish JaCoCo coverage report
                    jacoco execPattern: 'my-webapp/target/jacoco.exec', classPattern: 'my-webapp/target/classes', sourcePattern: 'my-webapp/src/main/java', exclusionPattern: ''
                }
            }
        }
    }
}
